name: simple CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: [ubuntu-latest, windows-latest]
    steps:
      - uses: actions/checkout@v2

      - name: Run build
        run: ./gradlew build

      - name: Run tests
        run: ./gradlew test

      - name: Run detekt
        run: ./gradlew detekt
